# Generated by Django 4.1.1 on 2022-12-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionhistory',
            options={'verbose_name': 'История действий', 'verbose_name_plural': 'История действий'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.CharField(default='https://www.meme-arsenal.com/memes/723c78e9be76eba2598c2d4c611f994c.jpg', max_length=500, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания аккаунта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен в'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='Заявка создана в'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='solution',
            field=models.BooleanField(blank=True, null=True, verbose_name='Решение врача'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Заявка обновлена в'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.CharField(max_length=40, verbose_name='Время посещения'),
        ),
    ]
