# Generated by Django 4.1.1 on 2022-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_actionhistory_options_alter_visit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специальность'),
        ),
    ]
