# Generated by Django 4.1.1 on 2022-12-17 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_customuser_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30, verbose_name='Цена за ваши услуги от и до')),
                ('whatsapp', models.CharField(max_length=50, verbose_name="Ваш номер whatsapp'a")),
                ('telegram', models.CharField(max_length=50, verbose_name='Ваш username телеграмма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Персонал')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
    ]
