# Generated by Django 4.1.1 on 2022-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.CharField(default=1, max_length=400, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
