# Generated by Django 4.1.1 on 2022-09-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.CharField(choices=[('Терапия', 'Терапия'), ('Кардиология', 'Кардиология'), ('Неврология', 'Неврология'), ('Хирургическая', 'Хирургическая'), ('Эндокринология', 'Эндокринология')], default=1, max_length=50, verbose_name='Отделение'),
            preserve_default=False,
        ),
    ]
