# Generated by Django 4.1.1 on 2022-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_service_options_service_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='solution',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Решение врача'),
        ),
    ]
