# Generated by Django 4.1.1 on 2022-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_patient_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chamber',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер палаты'),
            preserve_default=False,
        ),
    ]
