# Generated by Django 4.1.1 on 2022-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patient_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chamber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Палата'),
        ),
    ]
