# Generated by Django 4.1.1 on 2022-09-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_patient_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='branch',
            field=models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Терапия', 'Терапия'), ('Кардиология', 'Кардиология'), ('Неврология', 'Неврология'), ('Хирургическая', 'Хирургическая'), ('Эндокринология', 'Эндокринология')], max_length=50, verbose_name='Отделение'),
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Действие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
        ),
    ]
