# Generated by Django 4.1.1 on 2022-09-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_patient_branch_actionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient', verbose_name='Пациент'),
        ),
    ]
